services:
  ocr-ktp:
    build:
      context: .
      dockerfile: dockerfile
    container_name: ocr-ktp
    ports:
      - "127.0.0.1:${PORT:-8011}:${PORT:-8011}"
    volumes:
      - ./logs:/app/logs
      - ./app:/app/app
    env_file:
      - .env
    environment:
      - OMP_THREAD_LIMIT=6
      - OMP_NUM_THREADS=4
      - OPENBLAS_NUM_THREADS=4
      - MKL_NUM_THREADS=4
      - NUMEXPR_NUM_THREADS=4
      - OMP_WAIT_POLICY=PASSIVE
      - OMP_DYNAMIC=FALSE
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '7.5'
          memory: 8192M
        reservations:
          cpus: '4.0'
          memory: 2048M