services:
  ocr-ktp:
    build:
      context: .
      dockerfile: dockerfile
    container_name: ocr-ktp
    ports:
      - "127.0.0.1:${PORT:-8011}:${PORT:-8011}"
    volumes:
      - ./logs:/app/logs
      - ./app:/app/app
      - ./main.py:/app/main.py
    env_file:
      - .env
    environment:
      - OMP_THREAD_LIMIT=1
      - OMP_NUM_THREADS=1
      - OPENBLAS_NUM_THREADS=1
      - MKL_NUM_THREADS=1
      - NUMEXPR_NUM_THREADS=1
      - OMP_WAIT_POLICY=PASSIVE
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 2048M
        reservations:
          cpus: '2.0'
          memory: 512M